### ISSUE TITLE
Delete first line of app.js

### ISSUE THREAD

**Issue by kavishjadon** [kavishjadon/opensource#1]

**Comment by shubhamjadon** [comment]
Hey, there is no description. can you explain what is the issue?

**Comment by kavishjadon** [comment]
> Hey, there is no description. can you explain what is the issue?

This bug doesn't need a description

**Comment by shubhamjadon** [comment]
I claim it.

**Comment by kavishjadon** [comment]
#2 Closing on behalf of this.
