### ISSUE TITLE
Make algorithms

### ISSUE THREAD

**Issue by kavishjadon** [kavishjadon/opensource#3]
So, I was wondering if anyone can contribute some algorithms to this repository.
Programs can be in any language.
Write 'I claim' if you want this issue.

**Comment by shubhamjadon** [comment]
what type of algorithm.

**Comment by kavishjadon** [comment]
Any cs algorithms like insertion sort, bubble sort etc.

**Comment by shubhamjadon** [comment]
i would like to claim it.

**Comment by kavishjadon** [comment]
Write 'I claim'

**Comment by shubhamjadon** [comment]
I claim

**Comment by kavishjadon** [comment]
make it fast..

**Comment by kavishjadon** [comment]
Issue solved #6
